# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 18:38
from __future__ import unicode_literals

from django.db import migrations
import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='video_blob',
            field=utilities.models.BlobField(blank=True, verbose_name='VideoBlob'),
        ),
    ]
