# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180411_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='mime_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='VideoBlob'),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='video_blob',
            field=models.TextField(blank=True, verbose_name='VideoBlob'),
        ),
    ]
