# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_related_target', to='posts.PostItem', verbose_name='TARGET_LABEL'),
        ),
    ]
